### PR TITLE
Closes justicehub-in/Justice-Hub#71: Change look and feel of partner edit page

### PR DESCRIPTION
**Pull request by Abhi2102**
Screenshot from 2020-05-22 18-08-26
Screenshot from 2020-05-22 18-08-38

### CODE REVIEW

**Comment by Desingneer** [comment]
Partner Edit Page

1. Can we keep the logos on White backdrop
2. Keep the name of organisation as show here

looks neater

**Comment by curioswati** [comment]
**Info Tab**
image

**Edit Datasets Tab**

image


* The upload button can't be shifted to left since it's universally place on right across the site.
* The left bar will get update as part of another PR  for justicehub-in/Justice-Hub#55 so not updating here.
* the page only have the dataset title so can't add all other meta info in the edit page and it also doesn't make sense to have it here.
* @Deepthi-Chand had proposed to move the members tab to partner view page instead of manage mode so removed from here.
* There's no reorder functionality on the page so can't have that button.
* Update button is not available on dataset edit tab, it's available as 'Save Organization' on `Info` tab and is kept consistent with other form actions on other pages like `Add Dataset`
* The search bar has sorting on the right across site and is a common element being modified, can't add the `View` button specifically here and doesn't make sense either.

@Desingneer

**Comment by Desingneer** [comment]
@curioswati @Deepthi-Chand 
- _@Deepthi-Chand had proposed to move the members tab to partner view page instead of manage mode so removed from here._ How does one edit Members?
- Make _Save Organisation_ as a button, as it now appears like the Next>>
- _the page only have the dataset title so can't add all other meta info in the edit page and it also doesn't make sense to have it here._How does one edit a Dataset/Metadata, are they redirected to the Manage Dataset page?

**Comment by curioswati** [comment]
@curioswati @Deepthi-Chand

>>     * @Deepthi-Chand had proposed to move the members tab to partner view page instead of manage mode so removed from here.
> How does one edit Members?

On the org page, there will be a members tab. if a user is logged in they can edit from there itself instead having to go on a manage mode separately and then editing.

> >    * Make _Save Organisation_ as a button, as it now appears like the Next>>
>> 
> >    * _the page only have the dataset title so can't add all other meta info in the edit page and it also doesn't make sense to have it here.

> How does one edit a Dataset/Metadata, are they redirected to the Manage Dataset page?

yup.

@Desingneer

**Comment by curioswati** [comment]
fixed via #22

**Pull request merged**
